databases:
  - name: server-talis
    plan: free
    databaseName: dbname_77xc
    user: dbname_77xc_user

services:
  - type: web
    plan: free
    name: backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: server-talis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
