# Generated by Django 5.0.5 on 2024-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_boardgame_delete_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='year_published',
            field=models.SmallIntegerField(null=True),
        ),
    ]
