# Generated by Django 5.0.5 on 2024-06-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_boardgame_image_url_alter_boardgame_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
