# Generated by Django 5.0.5 on 2024-06-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_boardgame_created_at_boardgame_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
