# Generated by Django 5.0.5 on 2024-07-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_category_mechanic_publisher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgameexpansion",
            name="expansion_board_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_game_expansions",
                to="app.boardgame",
            ),
        ),
    ]
