# Generated by Django 5.0.5 on 2024-07-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_boardgameexpansion_expansion_board_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardgame",
            name="category",
        ),
        migrations.RemoveField(
            model_name="boardgame",
            name="expansion",
        ),
        migrations.RemoveField(
            model_name="boardgame",
            name="mechanic",
        ),
    ]
