# Generated by Django 5.0.5 on 2024-07-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_boardgame_category_remove_boardgame_expansion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardgame",
            name="publisher",
        ),
    ]
