# Generated by Django 5.0.5 on 2024-07-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_registereduser"),
        ("app", "0009_remove_boardgame_publisher"),
    ]

    operations = []
