# Generated by Django 5.0.5 on 2024-09-02 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userboardgamecollection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userboardgamecollection',
            unique_together={('user', 'board_game', 'status')},
        ),
    ]
