# Generated by Django 5.0.5 on 2024-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userboardgamecollection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboardgamecollection',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('library', 'Library')], max_length=20),
        ),
    ]
