# Generated by Django 5.0.5 on 2024-09-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userboardgamecollection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboardgamecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registereduser'),
        ),
    ]
