# Generated by Django 5.0.5 on 2024-10-08 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_logerror'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=32, null=True)),
                ('street', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('max_players', models.PositiveSmallIntegerField(default=0, null=True)),
                ('event_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('board_games', models.ManyToManyField(to='app.boardgame')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='app.category')),
            ],
        ),
    ]
