# Generated by Django 5.0.5 on 2024-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_logerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
