# Generated by Django 5.0.5 on 2024-10-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_event'),
        ('app', '0018_friendlist'),
    ]

    operations = [
    ]
