# Generated by Django 5.0.5 on 2024-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_0017_event_0018_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinates',
            field=models.JSONField(null=True),
        ),
    ]
