# Generated by Django 5.0.5 on 2024-10-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_event_coordinates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['rating'], name='app_boardga_rating_0a9758_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['name'], name='app_boardga_name_669693_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['min_players'], name='app_boardga_min_pla_bbe2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['max_players'], name='app_boardga_max_pla_5d44ba_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['age'], name='app_boardga_age_5f0b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['min_playtime'], name='app_boardga_min_pla_1f9957_idx'),
        ),
        migrations.AddIndex(
            model_name='boardgame',
            index=models.Index(fields=['max_playtime'], name='app_boardga_max_pla_ad3c23_idx'),
        ),
    ]
