# Generated by Django 5.0.5 on 2024-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_boardgame_app_boardga_rating_0a9758_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='cluster',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
