# Generated by Django 5.0.5 on 2024-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_boardgame_app_boardga_rating_0a9758_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(),
        ),
    ]
