# Generated by Django 5.0.5 on 2024-10-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_event_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='cookie_consent',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
