# Generated by Django 5.0.5 on 2024-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_commentsratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsratings',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='commentsratings',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
