from django.db import models
from models.board_game import BoardGame
from models.publisher import Publisher
from models.category import Category
from models.mechanic import Mechanic
from models.board_game_publisher import BoardGamePublisher
from models.board_game_category import BoardGameCategory
from models.board_game_mechanic import BoardGameMechanic
from models.board_game_expansion import BoardGameExpansion
from models.registered_user import RegisteredUser
