name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy frontend to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          app_name: 'talis'
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
