name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: 'talis'
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          spec: |
            name: talis
            services:
              - name: web
                github:
                  repo: talis
                  branch: main
                build_command: |
                  cd frontend && npm install && npm run build && cd ..
                  # Add any other build steps for your Django app here
                run_command: python manage.py runserver 0.0.0.0:8080
                envs:
                  - key: DJANGO_SETTINGS_MODULE
                    value: myapp.settings