name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: local
          POSTGRES_DB: db_dev
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.6.1 poetry-core==1.5.0
          poetry install -vvv

      - name: Debug Poetry and Environment
        run: |
          poetry --version
          poetry about
          poetry env list

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:local@localhost:5432/db_dev
        run: |
          poetry run pytest
