name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build React app
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/action-do-app-deploy@v2
        with:
          app_id: ${{ secrets.DIGITALOCEAN_APP_ID }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
