name: Run Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: local
          POSTGRES_DB: db_dev
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests and generate JUnit report
        env:
          DATABASE_URL: postgres://postgres:local@localhost:5432/db_dev
        run: |
          poetry run pytest --junitxml=pytest_report.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: pytest_report.xml

      - name: Report test results
        uses: dorny/test-reporter@v1
        with:
          name: Pytest Tests
          path: pytest_report.xml
          reporter: junit
          fail-on-error: true
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-empty: true
          only-summary: false