name: Run Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: local
          POSTGRES_DB: db_dev
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests and generate JUnitXML report
        env:
          DATABASE_URL: postgres://postgres:local@localhost:5432/db_dev
        run: |
          mkdir -p test-results
          poetry run pytest --junitxml=test-results/results.xml -v

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/results.xml

      - name: Annotate test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: test-results/results.xml
          reporter: junit
