name: Run Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: local
          POSTGRES_DB: db_dev
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install pytest plugins for better reporting
        run: |
          poetry add pytest-split pytest-check

      - name: Run tests with verbose output
        env:
          DATABASE_URL: postgres://postgres:local@localhost:5432/db_dev
        run: |
          poetry run pytest -v --tb=short --maxfail=1
